spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: james
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/