server:
  port: 0

spring:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: notification

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
