server:
  port: 8900

spring:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
#
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/