spring:
  application:
    name: todo-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: todolist-db

server:
  port: 8950

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
