spring:
  application:
    name: todo-service
  data:
    mongodb:
      database: todolist-db
      host: localhost
      port: 27017

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
