/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.developer.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmailDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8328127998493292460L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmailDetails\",\"namespace\":\"io.confluent.developer.avro\",\"fields\":[{\"name\":\"receiverEmail\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"senderEmail\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"receiverFirstName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"receiverLastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"senderFirstName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"senderLastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"date\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"time\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmailDetails> ENCODER =
      new BinaryMessageEncoder<EmailDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmailDetails> DECODER =
      new BinaryMessageDecoder<EmailDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmailDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmailDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmailDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmailDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmailDetails from a ByteBuffer. */
  public static EmailDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence receiverEmail;
  @Deprecated public java.lang.CharSequence senderEmail;
  @Deprecated public java.lang.CharSequence receiverFirstName;
  @Deprecated public java.lang.CharSequence receiverLastName;
  @Deprecated public java.lang.CharSequence senderFirstName;
  @Deprecated public java.lang.CharSequence senderLastName;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence date;
  @Deprecated public java.lang.CharSequence time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmailDetails() {}

  /**
   * All-args constructor.
   * @param receiverEmail The new value for receiverEmail
   * @param senderEmail The new value for senderEmail
   * @param receiverFirstName The new value for receiverFirstName
   * @param receiverLastName The new value for receiverLastName
   * @param senderFirstName The new value for senderFirstName
   * @param senderLastName The new value for senderLastName
   * @param title The new value for title
   * @param description The new value for description
   * @param date The new value for date
   * @param time The new value for time
   */
  public EmailDetails(java.lang.CharSequence receiverEmail, java.lang.CharSequence senderEmail, java.lang.CharSequence receiverFirstName, java.lang.CharSequence receiverLastName, java.lang.CharSequence senderFirstName, java.lang.CharSequence senderLastName, java.lang.CharSequence title, java.lang.CharSequence description, java.lang.CharSequence date, java.lang.CharSequence time) {
    this.receiverEmail = receiverEmail;
    this.senderEmail = senderEmail;
    this.receiverFirstName = receiverFirstName;
    this.receiverLastName = receiverLastName;
    this.senderFirstName = senderFirstName;
    this.senderLastName = senderLastName;
    this.title = title;
    this.description = description;
    this.date = date;
    this.time = time;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return receiverEmail;
    case 1: return senderEmail;
    case 2: return receiverFirstName;
    case 3: return receiverLastName;
    case 4: return senderFirstName;
    case 5: return senderLastName;
    case 6: return title;
    case 7: return description;
    case 8: return date;
    case 9: return time;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: receiverEmail = (java.lang.CharSequence)value$; break;
    case 1: senderEmail = (java.lang.CharSequence)value$; break;
    case 2: receiverFirstName = (java.lang.CharSequence)value$; break;
    case 3: receiverLastName = (java.lang.CharSequence)value$; break;
    case 4: senderFirstName = (java.lang.CharSequence)value$; break;
    case 5: senderLastName = (java.lang.CharSequence)value$; break;
    case 6: title = (java.lang.CharSequence)value$; break;
    case 7: description = (java.lang.CharSequence)value$; break;
    case 8: date = (java.lang.CharSequence)value$; break;
    case 9: time = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'receiverEmail' field.
   * @return The value of the 'receiverEmail' field.
   */
  public java.lang.CharSequence getReceiverEmail() {
    return receiverEmail;
  }

  /**
   * Sets the value of the 'receiverEmail' field.
   * @param value the value to set.
   */
  public void setReceiverEmail(java.lang.CharSequence value) {
    this.receiverEmail = value;
  }

  /**
   * Gets the value of the 'senderEmail' field.
   * @return The value of the 'senderEmail' field.
   */
  public java.lang.CharSequence getSenderEmail() {
    return senderEmail;
  }

  /**
   * Sets the value of the 'senderEmail' field.
   * @param value the value to set.
   */
  public void setSenderEmail(java.lang.CharSequence value) {
    this.senderEmail = value;
  }

  /**
   * Gets the value of the 'receiverFirstName' field.
   * @return The value of the 'receiverFirstName' field.
   */
  public java.lang.CharSequence getReceiverFirstName() {
    return receiverFirstName;
  }

  /**
   * Sets the value of the 'receiverFirstName' field.
   * @param value the value to set.
   */
  public void setReceiverFirstName(java.lang.CharSequence value) {
    this.receiverFirstName = value;
  }

  /**
   * Gets the value of the 'receiverLastName' field.
   * @return The value of the 'receiverLastName' field.
   */
  public java.lang.CharSequence getReceiverLastName() {
    return receiverLastName;
  }

  /**
   * Sets the value of the 'receiverLastName' field.
   * @param value the value to set.
   */
  public void setReceiverLastName(java.lang.CharSequence value) {
    this.receiverLastName = value;
  }

  /**
   * Gets the value of the 'senderFirstName' field.
   * @return The value of the 'senderFirstName' field.
   */
  public java.lang.CharSequence getSenderFirstName() {
    return senderFirstName;
  }

  /**
   * Sets the value of the 'senderFirstName' field.
   * @param value the value to set.
   */
  public void setSenderFirstName(java.lang.CharSequence value) {
    this.senderFirstName = value;
  }

  /**
   * Gets the value of the 'senderLastName' field.
   * @return The value of the 'senderLastName' field.
   */
  public java.lang.CharSequence getSenderLastName() {
    return senderLastName;
  }

  /**
   * Sets the value of the 'senderLastName' field.
   * @param value the value to set.
   */
  public void setSenderLastName(java.lang.CharSequence value) {
    this.senderLastName = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.CharSequence getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.CharSequence value) {
    this.time = value;
  }

  /**
   * Creates a new EmailDetails RecordBuilder.
   * @return A new EmailDetails RecordBuilder
   */
  public static io.confluent.developer.avro.EmailDetails.Builder newBuilder() {
    return new io.confluent.developer.avro.EmailDetails.Builder();
  }

  /**
   * Creates a new EmailDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmailDetails RecordBuilder
   */
  public static io.confluent.developer.avro.EmailDetails.Builder newBuilder(io.confluent.developer.avro.EmailDetails.Builder other) {
    return new io.confluent.developer.avro.EmailDetails.Builder(other);
  }

  /**
   * Creates a new EmailDetails RecordBuilder by copying an existing EmailDetails instance.
   * @param other The existing instance to copy.
   * @return A new EmailDetails RecordBuilder
   */
  public static io.confluent.developer.avro.EmailDetails.Builder newBuilder(io.confluent.developer.avro.EmailDetails other) {
    return new io.confluent.developer.avro.EmailDetails.Builder(other);
  }

  /**
   * RecordBuilder for EmailDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmailDetails>
    implements org.apache.avro.data.RecordBuilder<EmailDetails> {

    private java.lang.CharSequence receiverEmail;
    private java.lang.CharSequence senderEmail;
    private java.lang.CharSequence receiverFirstName;
    private java.lang.CharSequence receiverLastName;
    private java.lang.CharSequence senderFirstName;
    private java.lang.CharSequence senderLastName;
    private java.lang.CharSequence title;
    private java.lang.CharSequence description;
    private java.lang.CharSequence date;
    private java.lang.CharSequence time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.developer.avro.EmailDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.receiverEmail)) {
        this.receiverEmail = data().deepCopy(fields()[0].schema(), other.receiverEmail);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.senderEmail)) {
        this.senderEmail = data().deepCopy(fields()[1].schema(), other.senderEmail);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.receiverFirstName)) {
        this.receiverFirstName = data().deepCopy(fields()[2].schema(), other.receiverFirstName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.receiverLastName)) {
        this.receiverLastName = data().deepCopy(fields()[3].schema(), other.receiverLastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.senderFirstName)) {
        this.senderFirstName = data().deepCopy(fields()[4].schema(), other.senderFirstName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.senderLastName)) {
        this.senderLastName = data().deepCopy(fields()[5].schema(), other.senderLastName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.description)) {
        this.description = data().deepCopy(fields()[7].schema(), other.description);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.date)) {
        this.date = data().deepCopy(fields()[8].schema(), other.date);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.time)) {
        this.time = data().deepCopy(fields()[9].schema(), other.time);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmailDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.developer.avro.EmailDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.receiverEmail)) {
        this.receiverEmail = data().deepCopy(fields()[0].schema(), other.receiverEmail);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.senderEmail)) {
        this.senderEmail = data().deepCopy(fields()[1].schema(), other.senderEmail);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.receiverFirstName)) {
        this.receiverFirstName = data().deepCopy(fields()[2].schema(), other.receiverFirstName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.receiverLastName)) {
        this.receiverLastName = data().deepCopy(fields()[3].schema(), other.receiverLastName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.senderFirstName)) {
        this.senderFirstName = data().deepCopy(fields()[4].schema(), other.senderFirstName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.senderLastName)) {
        this.senderLastName = data().deepCopy(fields()[5].schema(), other.senderLastName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.title)) {
        this.title = data().deepCopy(fields()[6].schema(), other.title);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.description)) {
        this.description = data().deepCopy(fields()[7].schema(), other.description);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.date)) {
        this.date = data().deepCopy(fields()[8].schema(), other.date);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.time)) {
        this.time = data().deepCopy(fields()[9].schema(), other.time);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'receiverEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceiverEmail() {
      return receiverEmail;
    }

    /**
      * Sets the value of the 'receiverEmail' field.
      * @param value The value of 'receiverEmail'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setReceiverEmail(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.receiverEmail = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverEmail' field has been set.
      * @return True if the 'receiverEmail' field has been set, false otherwise.
      */
    public boolean hasReceiverEmail() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'receiverEmail' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearReceiverEmail() {
      receiverEmail = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderEmail() {
      return senderEmail;
    }

    /**
      * Sets the value of the 'senderEmail' field.
      * @param value The value of 'senderEmail'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setSenderEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.senderEmail = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'senderEmail' field has been set.
      * @return True if the 'senderEmail' field has been set, false otherwise.
      */
    public boolean hasSenderEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'senderEmail' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearSenderEmail() {
      senderEmail = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'receiverFirstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceiverFirstName() {
      return receiverFirstName;
    }

    /**
      * Sets the value of the 'receiverFirstName' field.
      * @param value The value of 'receiverFirstName'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setReceiverFirstName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.receiverFirstName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverFirstName' field has been set.
      * @return True if the 'receiverFirstName' field has been set, false otherwise.
      */
    public boolean hasReceiverFirstName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'receiverFirstName' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearReceiverFirstName() {
      receiverFirstName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'receiverLastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getReceiverLastName() {
      return receiverLastName;
    }

    /**
      * Sets the value of the 'receiverLastName' field.
      * @param value The value of 'receiverLastName'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setReceiverLastName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.receiverLastName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverLastName' field has been set.
      * @return True if the 'receiverLastName' field has been set, false otherwise.
      */
    public boolean hasReceiverLastName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'receiverLastName' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearReceiverLastName() {
      receiverLastName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderFirstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderFirstName() {
      return senderFirstName;
    }

    /**
      * Sets the value of the 'senderFirstName' field.
      * @param value The value of 'senderFirstName'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setSenderFirstName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.senderFirstName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'senderFirstName' field has been set.
      * @return True if the 'senderFirstName' field has been set, false otherwise.
      */
    public boolean hasSenderFirstName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'senderFirstName' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearSenderFirstName() {
      senderFirstName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderLastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderLastName() {
      return senderLastName;
    }

    /**
      * Sets the value of the 'senderLastName' field.
      * @param value The value of 'senderLastName'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setSenderLastName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.senderLastName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'senderLastName' field has been set.
      * @return True if the 'senderLastName' field has been set, false otherwise.
      */
    public boolean hasSenderLastName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'senderLastName' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearSenderLastName() {
      senderLastName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }

    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.title = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearTitle() {
      title = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.description = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearDescription() {
      description = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.date = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearDate() {
      date = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.CharSequence getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder setTime(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.time = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public io.confluent.developer.avro.EmailDetails.Builder clearTime() {
      time = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmailDetails build() {
      try {
        EmailDetails record = new EmailDetails();
        record.receiverEmail = fieldSetFlags()[0] ? this.receiverEmail : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.senderEmail = fieldSetFlags()[1] ? this.senderEmail : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.receiverFirstName = fieldSetFlags()[2] ? this.receiverFirstName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.receiverLastName = fieldSetFlags()[3] ? this.receiverLastName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.senderFirstName = fieldSetFlags()[4] ? this.senderFirstName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.senderLastName = fieldSetFlags()[5] ? this.senderLastName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.title = fieldSetFlags()[6] ? this.title : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.description = fieldSetFlags()[7] ? this.description : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.date = fieldSetFlags()[8] ? this.date : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.time = fieldSetFlags()[9] ? this.time : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmailDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmailDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmailDetails>
    READER$ = (org.apache.avro.io.DatumReader<EmailDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
