spring:
  application:
    name: keycloak-service

keycloak:
  realm: todolist
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}
  resource: todolist-app


server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}

